arren = Investor.create(name: "Arren Alexander", username: 'arren', interests: 'Outdoors, Software, Music, Travel', password: 'arren', mission: "Help exciting new companies grow", description: "Small investing firm looking for new investment opportunities", logo: 'https://images.unsplash.com/photo-1504670073073-6123e39e0754?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=23c233a430f2ca6be8d78f8608b416d5&auto=format&fit=crop&w=1050&q=80', url: 'https://www.linkedin.com/in/arren-alexander-10a361124', funds_to_invest: 1200000)
ryan = Investor.create(name: "Ryan Farney", username: 'ryan', interests: 'Sports, Software, Technology, Marketing', password: 'ryan', mission: "Gettin this money", description: "Big investing firm looking make cash baby", logo: 'https://images.unsplash.com/photo-1518169640858-0d622b058e5c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=5ffa10ff5bac3a77cb7de6e4e7164787&auto=format&fit=crop&w=1083&q=80', url: 'https://www.linkedin.com/in/ryanfarney3/', funds_to_invest: 500000)

company1 = StartUp.create(name: "Pilotworks", username: 'pilotworks', password: 'pilotworks', mission: "We help people start and scale quality food brands", description: "Pilotlight is a network of delightful cooking spaces, expert mentors, and inspiring entrepreneurs.

We operate beautiful, shared commissary spaces that entrepreneurs can rent to scale up their production and launch nascent food enterprises. We create community through our shared co-working spaces, events, and cross-promotional activities. We also have 75+ mentors that cover a wide range of topics, from fundraising and accounting to legal and social media strategy. Pilotlight also operates a full software platform for food businesses to connect with other folks in the industry.", field: "Food", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/841426-94245dbe501e97d46aa4dd8618c81b01-medium_jpg.jpg?buster=1511360348', url: 'https://www.thepilotworks.com', funds_needed: 31000)

company2 = StartUp.create(name: "Blend", username: 'blend', password: 'blend', mission: "Make the consumer lending ecosystem more transparent and accessible", description: "At Blend, we’re building a digital platform for lenders and borrowers that makes the experience more modern, transparent, and accessible to traditionally underserved customers. Our platform that vastly simplifies the loan application process and includes a simple, responsive, borrower platform and a full-featured lender experience. Blend engineers work across the enterprise and consumer software.", field: "Finance", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/91411-deb21e11105ced197c814683aa94bfe2-medium_jpg.jpg?buster=1498761293', url: 'https://blend.com', funds_needed: 15000)

company3 = StartUp.create(name: "Morty", username: 'morty', password: 'morty', mission: "Your smart home mortgage. We're hiring!", description: "Morty is on a mission to revolutionize the outdated mortgage industry by letting people shop, compare, and close on any mortgage from any lender, completely online. Purchasing a home is the largest, most important financial transaction of most people’s lives. We believe getting a mortgage should be just as simple, modern, and transparent as buying anything else online. We’re building the first-ever, fully digital marketplace to make this possible - Kayak, but for mortgages.", field: "Finance", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/1450851-7f969ba19a69411e15fe81ceff0b2293-medium_jpg.jpg?buster=1492707069', url: 'https://himorty.com/', funds_needed: 45000)

company4 = StartUp.create(name: "Localize", username: 'localize', password: 'localize', mission: "Localization as a Service", description: "Expanding globally is key to growth of any company, but is more complex and expensive than it should be.

Localize automates translation and seamlessly delivers those to the end-user, without code modifications (like Optimizely).", field: "Technology", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/376679-ca0abd1a7bf81d02219a13f5a16d4fb2-medium_jpg.jpg?buster=1453247831', url: 'https://localizejs.com', funds_needed: 23000)

company5 = StartUp.create(name: "HyperScience", username: 'hyperscience', password: 'hyperscience', mission: "AI for office work", description: "Our software enables some customers to automate processes and reallocate resources. Others leverage our tools to deliver life-saving benefits to those in need swiftly. ", field: "Technology", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/527650-fc82b293e25d46b78f48e85bd1082cab-medium_jpg.jpg?buster=1513695370', url: 'https://www.hyperscience.com/', funds_needed: 52000)

company6 = StartUp.create(name: "Zocdoc", username: 'zocdoc', password: 'zocdoc', mission: "Zocdoc is the tech company at the beginning of a better healthcare experience.", description: "Each month, millions of patients use Zocdoc to find in-network neighborhood doctors, instantly book appointments online, see what other real patients have to say, get reminders for upcoming appointments and preventive check-ups, fill out their paperwork online, and more. With a mission to give power to the patient, Zocdoc’s online marketplace delivers the accessible, seamless, and simple experience patients expect and deserve.", field: "Healthcare", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/32840-5b6d97504fb385656f0547977f61aca5-medium_jpg.jpg?buster=1463455142', url: 'https://www.zocdoc.com', funds_needed: 18000)

company7 = StartUp.create(name: "Wonolo", username: 'wonolo', password: 'wonolo', mission: "Fast. Flexible. Staffing Reinvented.", description: "We solve the last mile staffing problem for Fortune 500 companies as well as Small-to-Medium businesses (think Coca-Cola merchandising, eCommerce fulfillment, Event staffing, Hotel housekeeping, etc). Wonolo allows companies to manage unpredictability by augmenting their existing labor force with hourly to daily Wonoloers who can come in within an hour and do the job. ", field: "Staffing", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/377879-494a4296adb63987d90171fb302e6fa9-medium_jpg.jpg?buster=1405059868', url: 'https://wonolo.com', funds_needed: 30000)

company8 = StartUp.create(name: "Truly", username: 'truly', password: 'truly', mission: "Make Calling Your Competitive Advantage", description: "Conversations are the foundation for doing business.

Founded in 2013, Truly is the premier enterprise voice system for sales, account management, and customer success teams. ", field: "Technology", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/204827-aaa55ed57eaf35bc82ad1ffeffa848be-medium_jpg.jpg?buster=1515625410', url: 'https://www.truly.co', funds_needed: 55000)

company10 = StartUp.create(name: "MakeSpace", username: 'makespace', password: 'makespace', mission: "Your Closet in the Cloud", description: "MakeSpace is Your Closet in the Cloud (TM) -- convenient, simple, on-demand storage solution that takes the self out of self storage. Our customers literally never have to visit a self-storage facility again without sacrificing knowing what they've put away.
", field: "E-Commerce", logo: 'https://d1qb2nb5cznatu.cloudfront.net/startups/i/260840-95db95ab15a51b3b52755dea714ca30b-medium_jpg.jpg?buster=1392955319', url: 'https://makespace.com/', funds_needed: 45000)
